"""Generate docker-compose.roots.yml from ALLOWED_DOC_ROOTS in .env (host-side, stdlib only).

Each root is bind-mounted read-only at /roots/<alias> into the api and worker containers.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(REPO, "backend"))

from app.rootmap import parse_roots  # noqa: E402


def read_env(path: str) -> dict[str, str]:
    env = {}
    if os.path.exists(path):
        with open(path, encoding="utf-8-sig") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def main() -> int:
    env = read_env(os.path.join(REPO, ".env"))
    roots = parse_roots(env.get("ALLOWED_DOC_ROOTS", ""))
    lines = ["# Generated by scripts/gen_roots.py from ALLOWED_DOC_ROOTS — do not edit.", "services:"]
    mounts = []
    for r in roots:
        if r.kind == "unc":
            print(f"warning: {r.host} is a network (UNC) path. Docker Desktop can't bind-mount it directly; "
                  "map it to a drive letter or mount it on the host first. Skipped.", file=sys.stderr)
            continue
        mounts.append(f'      - "{r.mount_source()}:/roots/{r.alias}:ro"')
        print(f"root {r.host} -> /roots/{r.alias}")
    for svc in ("api", "worker"):
        lines.append(f"  {svc}:")
        lines.append("    volumes:" if mounts else "    volumes: []")
        lines.extend(mounts)
    with open(os.path.join(REPO, "docker-compose.roots.yml"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
